kitti_root: /media/qzj/Document/datasets/KITTI/odometry/data_odometry_velodyne/dataset/
apollo_root: /media/qzj/Document/datasets/Apollo
kitti360_root: /media/qzj/Document/datasets/KITTI-360
hit_root: /media/qzj/Document/datasets/HIT/dataset

sample_interval: 2 # meters for downsample
skip_frames: 250 # skip frames for loop closure detection

evaluation:
  rot_thd: 5 # the error between the estimated pose and GT shouldn't exceed 5 degrees
  trans_thd: 2 # the error between the estimated pose and GT shouldn't exceed 2 meters

fpfh:
  voxel_size: 0.3 # meter
  radius_normal: 1.0 # meter, for normal estimation
  radius_feature: 2.5 # meter, for feature estimation

teaser:
  noise_bound: 0.4 # meter

# configs of SC2_PCR_plusplus
CUDA_Devices: 1
num_iterations: 10
dataset: KITTI
ratio: 0.2
k1: 40
k2: 30
data_path: /media/qzj/Document/datasets/fpfh_test
descriptor: fpfh
inlier_threshold: 0.6
sigma_d: 0.6
d_thre: 0.1
downsample: 0.3
re_thre: 5
te_thre: 60
num_node: 8000
use_mutual: false
max_points: 8000
nms_radius: 0.3
FS_TCD_thre: 0.1
relax_match_num: 100
NS_by_IC: 50